project_settings/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()
urlpatterns = patterns('',

    # TeamHub custom URLs
    url(r'^$', 'teamhub.views.dashboard', name='home'),
    url(r'^aufgabe/(?P<aufgabeId>\d+)/$', 'teamhub.views.aufgabeDetails' , name='aufgabeDetails'),
    url(r'^aufgabe/offeneAufgaben/', 'teamhub.views.offeneAufgabenAnzeigen'),
    url(r'^aufgabe/vonMirErstellteAufgaben/', 'teamhub.views.vonMirErstellteAufgaben'),
    url(r'^profil/','teamhub.views.userProfilBearbeiten'),
    url(r'^projekte/(?P<projektId>\d+)/bearbeiten/$', 'teamhub.views.projektBearbeiten', name='projektBearbeiten'),
    url(r'^projekte/(?P<projektId>\d+)/$', 'teamhub.views.projektDetail', name='projektDetails'),
    url(r'^aufgabe/(?P<aufgabeId>\d+)/bearbeiten/$', 'teamhub.views.aufgabeBearbeiten', name='aufgabeBearbeiten'),
    url(r'^projekte/erstellen/','teamhub.views.projektErstellen'),
    url(r'^aufgabe/erstellen/','teamhub.views.aufgabeErstellen'),
    url(r'^projekte/','teamhub.views.projektListe'),
    url(r'^login/','django.contrib.auth.views.login'),
    url(r'^logout/','teamhub.views.logoutUser'),
    url(r'^benutzer/','teamhub.views.benutzerErstellen'),
    url(r'^suchen/','teamhub.views.aufgabeSuchen'),
    url(r'^passwaendern/','teamhub.views.passwortAendern'),
    url(r'^passwzurueck/','teamhub.views.passwortZuruecksetzen'),
    # Examples:
    # url(r'^project_settings/', include('project_settings.foo.urls')),

    # Admin urls
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),


    # Comments framework urls
    url(r'^comments/', include('django.contrib.comments.urls')),

)

teamhub/models.py
# coding: utf-8
"""
.. module:: models

:platform: Unix, Windows

:synopsis: Custom Django models für teamhub Paket.

.. moduleauthor:: Tim Jagodzinski


"""
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.utils import IntegrityError
import teamhub.stringConst as c
import re

# Enums used by model classes
PRIORITAET = (
    (c.PRIORITAET_HI, "Hoch"),
    (c.PRIORITAET_ME, "Mittel"),
    (c.PRIORITAET_LO, "Niedrig"),
)

AUFGABE_STATUS = (
    (c.AUFGABE_STATUS_OP, "Offen"),
    (c.AUFGABE_STATUS_IP, "In Bearbeitung"),
    (c.AUFGABE_STATUS_PA, "Angehalten"),
    (c.AUFGABE_STATUS_CL, "Geschlossen"),
)

PROJEKT_STATUS = (
    (c.PROJEKT_STATUS_OP, "Offen"),
    (c.PROJEKT_STATUS_CL, "Geschlossen"),
)

# App model classes


class TeamhubUser(User):
    '''
    Repräsentation eines Benutzers. Die Proxyklasse wird für erweiternde Funktionen verwendet,
    die über die von Django bereitgestellten hinausgehen.
    '''
    class Meta:
        proxy = True

    def save(self, *args, **kwargs):
        '''Überprüft den Benutzernamen auf nicht erlaubte Zeichen. Nur Benutzernamen, welche dem
        regulären Ausdruck r'^[\w.@+-]+$' folgen sind erlaubt.

        :throws IntegrityError: Falls das Feld unsername nicht erlaubte Zeichen enthält.

        '''
        pattern = re.compile(r'^[\w.@+-]+$')

        if not re.match(pattern, self.username):
            raise IntegrityError(c.FEHLER_TEAMHUBUSER_USERNAME_INVALID)
        super(TeamhubUser, self).save(*args, **kwargs)


class Projekt(models.Model):
    '''
    Repräsentation eines Projekts. Projekte werden zur Organisation von Aufgaben benutzt.
        .. py:attribute:: besitzer

        Fremdschlüssel, der auf ein TeamhubUser-Objekt verweist. Kann nicht mehr geändert werden.

        .. py:attribute:: name

        String, Name bzw. Titel des Projekts. Ist veränderbar.

        .. py:attribute:: beschreibung

        String, Ausführliche Beschreibung des Projekts. Ist veränderbar.

        .. py:attribute:: status

        String, Bearbeitungsstatus des Projekts. Kann nur die Werte "Offen" oder "Geschlossen" sein.

'''

    besitzer = models.ForeignKey(TeamhubUser, related_name="besitzer", help_text="Verantwortlicher für das Projekt.", blank=True, null=True)

    name = models.CharField(max_length=512, help_text="Name des Projekts.", unique=True)
    beschreibung = models.TextField(help_text="Ausführliche Beschreibung des Projekts.")
    status = models.CharField(max_length=2, default=c.PROJEKT_STATUS_OP, choices=PROJEKT_STATUS, help_text="Zustand des Projekts.")

    def __unicode__(self):
        return self.name


class Aufgabe(models.Model):

    '''Repräsentation einer Aufgabe.

        .. py:attribute:: ersteller

        Fremdschlüssel, verweist auf ein TeamhubUser-Objekt, ist unveränderbar.

        .. py:attribute:: bearbeiter

        Fremdschlüssel, verweist auf ein TeamhubUser-Objekt, ist veränderlich.

        .. py:attribute:: projekt

        Fremdschlüssel, verweist auf ein Projekt-Objekt, ist veränderlich.

        .. py:attribute:: status

        String, Bearbeitungsstatus der Aufgabe, kann je nach Zustand folgende Werte annehmen: "Offen", "In Bearbeitung", "Angehalten", "Geschlossen". Veränderlich.

        .. py:attribute:: prioritaet

        String, Bearbeitungspriorität der Aufgabe, kann die Werte "Niedrig", "Mittel", "Hoch" annehmen. Veränderlich.

        .. py:attribute:: titel

        String, Titel bzw. Kurzbeschreibung der Aufgabe, ist veränderlich.

        .. py:attribute:: beschreibung

        String, ausführliche Beschreibung der Aufgabe, ist veränderlich.

        .. py:attribute:: erstellDatum

        Datum, Zeitpunkt der Erstellung der Aufgabe, ist unveränderlich.

        .. py:attribute:: aenderungsDatum

        Datum, Zeitpunkt der letzten Änderung an der Aufgabe, wird automatisch vom System gesetzt.

        .. py:attribute:: faelligkeitsDatum

        Datum, Zeitpunkt zu dem die Aufgabe erfüllt sein soll, ist veränderlich.

'''
    ersteller = models.ForeignKey(TeamhubUser, related_name="ersteller", help_text="Ersteller dieser Aufgabe.", blank=True, null=True)
    bearbeiter = models.ForeignKey(TeamhubUser, related_name="bearbeiter", blank=True, null=True, help_text="Bearbeiter dieser Aufgabe.")
    projekt = models.ForeignKey(Projekt, related_name="projekt", help_text="Das der Aufgabe übergeordnete Projekt.")

    status = models.CharField(max_length=2, default=c.AUFGABE_STATUS_OP, choices=AUFGABE_STATUS, help_text="Bearbeitungsstatus der Aufgabe.")
    prioritaet = models.CharField(max_length=2, default=c.PRIORITAET_ME, choices=PRIORITAET, help_text="Priorität der Aufgabe im Hinblick auf das Projekt.")
    titel = models.CharField(max_length=512, help_text="Der Titel soll eine Idee des Inhalts der Aufgabe geben.")
    beschreibung = models.TextField(blank=True, help_text="Detaillierter Beschreibung der Aufgabe. Was ist das Problem? Unter welchen Bedingungen gilt die Aufgabe als gelöst?")
    erstellDatum = models.DateTimeField(auto_now_add=True, help_text="Die Aufgabe wurde an diesem Tag erstellt.")
    aenderungsDatum = models.DateTimeField(editable=False, auto_now=True, auto_now_add=True, help_text="Zeit der letzten Änderung.")
    faelligkeitsDatum = models.DateTimeField(blank=True, help_text="Die Aufgabe muss bis zu diesem Datum erledigt sein.")

    def save(self):
        '''
        Speichert das Objekt ab. Zuvor wird eine Reihe von Validierungen durchgeführt.

        Validierungen:

        * Name innerhalb des Projekts nicht eindeutig.
        * Fälligkeitsdatum liegt in der Vergangenheit.
        * Projekt ist bereits geschlossen.

        .. throws: IntegrityError Falls eine der Validierungen fehlschlägt.

        '''

        if Aufgabe.objects.filter(titel=self.titel, projekt=self.projekt).exclude(pk=self.pk).count() != 0:
            raise IntegrityError(c.FEHLER_AUFGABE_NAME)
        if self.faelligkeitsDatum < timezone.now():
            raise IntegrityError(c.FEHLER_AUFGABE_DATUM)
        if self.projekt.status == c.PROJEKT_STATUS_CL:
            raise IntegrityError(c.FEHLER_AUFGABE_PROJEKTSTATUS)
        if self.bearbeiter and self.status == c.AUFGABE_STATUS_OP:
            self.status = c.AUFGABE_STATUS_IP
        if not self.bearbeiter and self.status == c.AUFGABE_STATUS_IP:
            self.status = c.AUFGABE_STATUS_OP

        super(Aufgabe, self).save()

    def getStati(self):
        '''
        Erzeugt ein Dictionary mit erlaubten Status-Schlüsseln für die Anzeige in Formularen.

        Erlaubte Wege:

        .. image:: /img/status.png

        '''
        if self.status == c.AUFGABE_STATUS_OP:
            return dict(AUFGABE_STATUS[3:])
        if self.status == c.AUFGABE_STATUS_IP:
            return dict(AUFGABE_STATUS[2:])
        if self.status == c.AUFGABE_STATUS_PA:
            return dict(AUFGABE_STATUS[1:2])
        if self.status == c.AUFGABE_STATUS_CL:
            return dict(AUFGABE_STATUS[1:2])
        return{}

    def __unicode__(self):
        return self.titel

teamhub/forms.py
# coding: utf-8

"""
.. module:: forms

:platform: Unix, Windows

:synopsis: Custom Django forms für teamhub Paket.

.. moduleauthor:: Tim Jagodzinski


"""
from django import forms
from django.forms import ModelForm
from django.forms.widgets import PasswordInput

from teamhub.models import Projekt, Aufgabe, TeamhubUser


class profilForm(ModelForm):
    '''
    Eingabeformular zum Ändern des Benutzerprofils.
    '''
    class Meta:
        model = TeamhubUser
        fields = ('username', 'first_name', 'last_name', 'email')


class projektFormBearbeiten(ModelForm):
    '''
    Eingabeformular zum Bearbeiten eines Projekt-Objekts.
    '''
    class Meta:
        model = Projekt
        exclude = ('besitzer')


class projektFormErstellen(ModelForm):
    '''
    Eingabeformular zum Erstellen eines Projekt-Objekts.
    '''
    class Meta:
        model = Projekt
        exclude = ('status', 'besitzer')


class aufgabeForm(ModelForm):
    '''
    Eingabeformular zum Erstellen/Bearbeiten eines Aufgabe-Objekts.
    '''
    class Meta:
        model = Aufgabe
        exclude = ('ersteller', 'status',)


class userForm(ModelForm):
    '''
    Eingabeformular zum Erstellen/Ändern eines TeamhubUser-Objekts.
    '''
    class Meta:
        model = TeamhubUser
        fields = ('username', 'email', 'is_staff')


class passwortAendernForm(forms.Form):
    '''
    Eingabeformular zum Ändern des Passworts.
    '''
    passwAlt = forms.CharField(widget=PasswordInput, label="Altes Passwort", max_length=128, min_length=4)
    passwNeu1 = forms.CharField(widget=PasswordInput, label="Neues Passwort", max_length=128, min_length=4)
    passwNeu2 = forms.CharField(widget=PasswordInput, label="Neues Passwort widerholen", max_length=128, min_length=4)


class passwortZuruecksetzenForm(forms.Form):
    benutzerliste = forms.ModelChoiceField(queryset=TeamhubUser.objects.all())

teamhub/templates/base.html
{% load static from staticfiles %}
{% load filter %}

<!DOCTYPE html>
<html>
	 <style>
      body{
      	padding-top: 0,5%; /* 60px to make the container go all the way to the bottom of the topbar */
      	padding-left: 5%;
      	padding-right: 5%;
      }
    </style>
	<head>
		<title>TeamHub</title>
		<!-- Bootstrap -->
		<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

	</head>
	{% block sectionnavbar %}
	<body>
			<div class="navbar">
				<div class="navbar-inner">
					<a class="brand" href="/">TeamHub</a>
					<ul class="nav">
						<li class="dropdown">
							<a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-tasks"></i> Aufgaben <i class="caret"></i></a>
							<ul class="dropdown-menu">
								<!--li><a href="/">Meine Aufgaben</a></li>
								<li class="divider"></li-->
								<li>
									<a href="/">Meine Aufgaben</a>
								</li>
								<li>
									<a href="/aufgabe/offeneAufgaben/">Offene Aufgaben</a>
								</li>
								<li>
									<a href="/aufgabe/vonMirErstellteAufgaben/">Von mir erstellte Aufgaben</a>
								</li>
								<li>
									<a href="/aufgabe/erstellen/"><i class="icon-plus-sign"></i> Aufgabe erstellen</a>
								</li>
							</ul>
						</li>
						<li>
							<a href="/projekte/"><i class="icon-road"></i> Projekte</a>
						</li>
						<li class="dropdown">
							<a class="dropdown-toggle"
							data-toggle="dropdown" href="#"><i class="icon-user"></i> Mein Konto <i class="caret"></i></a>
							<ul class="dropdown-menu">
								<li>
									<a href="/profil/"><i class="icon-edit"></i> Profil bearbeiten</a>
								</li>
								<li class="divider"></li>
								<li>
								<li>
									<a href="/passwaendern/"><i class="icon-edit"></i> Passwort ändern</a>
								</li>
								<li class="divider"></li>
								<li>	
									
									<a href="/logout/"><i class="icon-off"></i> Abmelden</a>
								</li>
							</ul>
						</li>
						{% if user.is_staff %}
						<li class="dropdown">
							<a class="btn-danger dropdown-toggle "
							data-toggle="dropdown" href="#" style=" color: white;"><i class="icon-cog "></i> Admin Tools <i class="caret"></i></a>
								<ul class="dropdown-menu">
  									<li>
										<a href="/benutzer/"><i class="icon-user"></i> Benutzer erstellen</a>
									</li>
									<li>
										<a href="/passwzurueck/"><i class="icon-folder-close"></i> Passwort zurücksetzen</a>
									</li>
									<li class="divider"></li>
									<li>
										<a href="/projekte/erstellen/"><i class="icon-folder-close"></i> Projekt erstellen</a>
									</li>
  								</ul>
  						</li>
  					{%endif%}
					</ul>
						<form class="navbar-form pull-right" action="/suchen/" method="get">
						<select class="span2" name="projekt">
							<!--option>Projekt</option-->
							<option value="">Alle Projekte</option>
								{% for projekt in projektliste%}
							<option>{{projekt.name}}</option>
								{% endfor %}
  							<input class="span2" id="appendedInputButtons" type="text" placeholder="Aufgaben durchsuchen" name="search">
  								<button class="btn" type="submit">Search</button>
  						</select>
					</form>
				</div>
			</div>
			{% endblock %}

			<div class="page-header">
				<h1>{%block sectiontitle %}{{title}}{% endblock %}</h1>
			</div>
			{% block content %}
			{% endblock %}
			{% block liste %}
			{% endblock %}
			

		<!-- js loads at the end to load page faster -->
		<script src="{% static "js/jquery-1.8.2.min.js" %}"></script>
		<script src="{% static "js/bootstrap.min.js" %}"></script>
	</body>
</html>

teamhub/templates/base_aufgabe_bearbeiten.html
{% extends "base.html" %}
{% load url from future %}


{% block sectiontitle %}{{title}}{% endblock %}

{% block content %}

<form action="" method="post">
        {% csrf_token %}
    <p class="text-error">{{ form.non_field_errors|striptags }}</p>
    <div class="fieldWrapper">
       
        <label for="id_bearbeiter">Bearbeiter: </label>
                <p class="text-error">{{form.bearbeiter.errors|striptags}}</p>
                {{ form.bearbeiter }}
      
        <label for="id_projekt">Projekt:</label>
                <p class="text-error">{{form.projekt.errors|striptags}}</p>
                {{ form.projekt }}
    
        <label for="id_prioritaet">Priorität:</label>
                <p class="text-error">{{ form.prioritaet.errors|striptags }}</p>
                {{ form.prioritaet }}
   
        <label for="id_titel">Titel:</label>
                <p class="text-error">{{ form.titel.errors|striptags }}</p>
                {{ form.titel }}
   
        <label for="id_beschreibung">Beschreibung:</label>
                <p class="text-error">{{ form.beschreibung.errors|striptags }}</p>
                {{ form.beschreibung }}

        <label for="id_faelligkeitsdatum">Fälligkeitsdatum:</label>
                <p class="text-error">{{ form.faelligkeitsDatum.errors|striptags }}</p>
                {{ form.faelligkeitsDatum }}
   

     {%if stati%}
        <p>Status der Aufgabe ändern.</p>
        <select name="stati">
                <option value="{{aktuellerstatus}}">{{aktuellerstatus_lang}}</option>
                {%for key, value in stati.items%}
                        <option value="{{key}}">{{value}}</option>
                {%endfor%}
        </select>
        {%endif%}
     <br><br>
     <button class="btn btn-primary" type="submit">Senden</button>
  </div>
</form>

{% endblock %}

teamhub/templates/base_aufgabe_erstellen.html
{% extends "base.html" %}
{% load url from future %}

{% block sectiontitle %}{{title}}{% endblock %}


{% block content %}



<form action="" method="post">
	{% csrf_token %}
<p class="text-error">{{ form.non_field_errors|striptags }}</p>
   <div class="fieldWrapper">
        <p class="text-error">{{form.bearbeiter.errors|striptags}}</p>
        <label for="id_bearbeiter">Bearbeiter: </label>
        {{ form.bearbeiter }}
      
        <p class="text-error">{{form.projekt.errors|striptags}}</p>
        <label for="id_projekt">Projekt:</label>
        {{ form.projekt }}
    
    
        <p class="text-error">{{ form.prioritaet.errors|striptags }}</p>
        <label for="id_prioritaet">Priorität:</label>
        {{ form.prioritaet }}
   
  
        <p class="text-error">{{ form.titel.errors|striptags }}</p>
        <label for="id_titel">Titel:</label>
        {{ form.titel }}
   
    
        <p class="text-error">{{ form.beschreibung.errors|striptags }}</p>
        <label for="id_beschreibung">Beschreibung:</label>
        {{ form.beschreibung }}
   
     
        <p class="text-error">{{ form.faelligkeitsDatum.errors|striptags }}</p>
        <label for="id_faelligkeitsdatum">Fälligkeitsdatum:</label>
        {{ form.faelligkeitsDatum }}
   

        {%if stati%}
        <p>Status der Aufgabe ändern.</p>
        <select name="stati">
		  <option value="{{aktuellerstatus}}">{{aktuellerstatus_lang}}</option>
            {%for key, value in stati.items%}
            <option value="{{key}}">{{value}}</option>
            {%endfor%}
        </select>
        {%endif%}
        <br><br>
        <button class="btn btn-primary" type="submit">Senden</button>
  </div>
</form>

{% endblock %}

teamhub/templates/base_benutzer_erstellen.html
{% extends "base.html" %}
{% load url from future %}

{% block sectiontitle %}Benutzer erstellen{% endblock %}

{% block content %}

<form action="" method="post">
	{% csrf_token %}
  <p class="text-error">{{ form.non_field_errors|striptags }}</p>
	<label for="id_username">Benutzername: </label>
    	<p class="text-error">{{form.username.errors|striptags}}</p>
      	{{ form.username }}

    <label for="id_email">Email-Adresse:</label>
   		<p class="text-error">{{form.email.errors|striptags}}</p>
       	{{ form.email }}

    <label for="id_isStaff">Admin Berechtigungen?:</label>
   		<p class="text-error">{{form.is_staff.errors|striptags}}</p>
       	{{ form.is_staff }}

     <br><br>
     <button class="btn btn-primary" type="submit">Senden</button>
</form>  

{% endblock %}

teamhub/templates/base_passwortAendern.html
{% extends "base.html" %}
{% load url from future %}

{% block sectiontitle %}Passwort ändern{% endblock %}

{% block content %}

<form action="" method="post">
	{% csrf_token %}
  <p class="text-error">{{ form.non_field_errors|striptags }}</p>
   <div class="fieldWrapper">
        <p class="text-error">{{form.passwAlt.errors|striptags}}</p>
        <label for="id_passwAlt">Altes Passwort: </label>
        {{ form.passwAlt }}
      </div>
        <p class="text-error">{{form.passwNeu1.errors|striptags}}</p>
        <label for="id_passwNeu1">Neues Passwort: (min. 4 Zeichen)</label>
        {{ form.passwNeu1 }}
    </div>
    <div class="fieldWrapper">
        <p class="text-error">{{ form.passwNeu2.errors|striptags }}</p>
        <label for="id_passwNeu2">Neues Passwort widerholen:</label>
        {{ form.passwNeu2 }}
    </div>
     <button class="btn btn-primary" type="submit">Senden</button>
</form>

{% endblock %}

teamhub/templates/base_passwortZuruecksetzen.html
{% extends "base.html" %}
{% load url from future %}

{% block sectiontitle %}Passwort zurücksetzen {% endblock %}

{% block content %}

	<p>{{erfolg}}</p>

<form method="post" action="">
	{% csrf_token %}
	<p class="text-error">{{ form.non_field_errors|striptags }}</p> 
	 <div class="fieldWrapper">
        <p class="text-error">{{form.benutzerliste.errors|striptags}}</p>
        <label for="id_passwAlt">Benutzerliste: </label>      	
    {{ form.benutzerliste}}
    </div>
    <br><br>
    <button class="btn btn-primary" type="submit">Zurücksetzen</button>
</form>

{% endblock %}

teamhub/templates/base_projekt.html
{% extends "base.html" %}
{% load url from future %}

{% block sectiontitle %}Projektliste<br> 
{% endblock %}

{% block content %}

{% for projekt in projektliste %}

<ul class="thumbnails">
  <li class="span12">
    <div class="thumbnail" style="color: black; black;  border-width: 0; box-shadow: 4px 4px 4px #666;">
    	<table class="table">
	       <thead>
		        <th width="50%">Besitzer: {{projekt.besitzer}}</th>
		        <th>Status: {{projekt.get_status_display}}</th>
	       </thead>
      </table>
     <h3><a href="/projekte/{{projekt.pk}}/">{{projekt.name}}</a></h3>
     <p>{{projekt.beschreibung}}</p>
   </div>
  </li>
</ul>

{% endfor %}
{% endblock %}

teamhub/templates/base_projekt_bearbeiten.html
{% extends "base.html" %}
{% load url from future %}

{% block sectiontitle %}Projekt bearbeiten{% endblock %}

{% block content %}

<form action="" method="post">
	{% csrf_token %}
  <p class="text-error">{{ form.non_field_errors|striptags }}</p>
   	<label for="id_projektName">Name: </label>
      <p class="text-error">{{form.name.errors|striptags}}</p>
      {{ form.name }}

    <label for="id_beschreibung">Beschreibung:</label>
   	  <p class="text-error">{{form.beschreibung.errors|striptags}}</p>
      {{ form.beschreibung }}

    <label for="id_status">Status:</label>
   	  <p class="text-error">{{form.status.errors|striptags}}</p>
      {{ form.status }}

     <br><br>
     <button class="btn btn-primary" type="submit">Senden</button>
</form>
{% endblock %}

teamhub/templates/base_projekt_detail.html
{% extends "base.html" %}
{% load url from future %}
{% load filter %}

<h2>{% block sectiontitle %}Projekt{% endblock %}</h2>

{% block content %}
<div class="container">	
  <div class="hero-unit" style="color: black; black;  border-width: 0; box-shadow: 4px 4px 4px #666;" >
	{% if user.is_staff%}
      <p><a class="btn btn-primary btn-medium" href="/projekte/{{projekt.pk}}/bearbeiten/">Projekt bearbeiten &raquo;</a></p>
  {%endif%}
	 <table class="table table-striped table-hover">
    	<thead>
        	<th width="70%"><small>Besitzer: {{projekt.besitzer}}</small></th>
          <th><small>Status: {{projekt.get_status_display}}</small></th>
       	</thead>	
	 </table>
        <h2>{{projekt.name}}</h2>
        <p>{{projekt.beschreibung}}</p>
        
  </div>

  {% if projekt.status == 'CL'%}
  {% else %}
  <br/>
  <div class="Aufgaben">
    <h2>Aufgaben:</h2> 
    <br><a class="btn btn-primary btn-medium pull-left"  href="/aufgabe/erstellen/">Aufgabe erstellen</a>
    {%endif%}
    <br><br>
    <ul class="thumbnails">
	   {% for aufgabe in aufgaben %}
	   <li class="span12">
		    {% ifequal aufgabe.prioritaet prioritaet.0 %}
  	       <div class="thumbnail alert alert-error" style="color: black; black;  border-width: 0; box-shadow: 4px 4px 4px #666;">
  	    {%endifequal%}
        {% ifequal aufgabe.prioritaet prioritaet.1 %}
  	   			<div class="thumbnail alert alert-alert" style="color: black; black;  border-width: 0; box-shadow: 4px 4px 4px #666;">
  	   	{%endifequal%}
  	   	{% ifequal aufgabe.prioritaet prioritaet.2 %}
  	   			<div class="thumbnail alert alert-success" style="color: black; black;  border-width: 0; box-shadow: 4px 4px 4px #666;">
  	   	{%endifequal%}

        {% if aufgabe.status == 'OP' %}
          <p><a class="btn btn-success btn-mini pull-right" href="/aufgabe/{{aufgabe.pk}}/bearbeiten/">Aufgabe annehmen</a></p>
        {%endif%} 	

		          <table class="table table-striped ">
  				      <tbody>
  					       <th width="25%"><small>Ersteller: {{aufgabe.ersteller}}</small></th>
  					       <th width="25%"><small>Bearbeiter: {{aufgabe.bearbeiter}}</small></th>
  					       <th width="25%"><small>Status: {{ aufgabestatus_lang|getItem:aufgabe.status}}</small></th>
  					       {% if aufgabe.faelligkeitsDatum <= dateNow %}
                   <th width="20%" style="color: #FF0000;"><strong><small>{{ aufgabe.faelligkeitsDatum }}</strong></small></th>
                   {%else%}
                   <th width="20%"><small>{{ aufgabe.faelligkeitsDatum }}</th>
                  {%endif%}
  				      </tbody>	
  		        </table>
  		        <h3><a class="text-info" style="color: #6699CC;" href="/aufgabe/{{aufgabe.pk}}/"> {{aufgabe.titel}}</a></h3>			
      {% endfor %}
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock %}